cache: 
  paths:
    - backend/apis/node_modules/

.common_install: &common_install
  - cd backend/apis
  - npm i

test_lambda:
  stage: test
  image: node:20.11.1
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "staging"'
  #     changes:
  #       - backend/apis/**/*
  script:
    - *common_install
    - npm run test

build_staging:
  artifacts:
    expose_as: 'backend-build-staging'
    name: 'backend-build-staging'
    paths: 
      - $PWD/backend/apis/.serverless/jngpaypal.zip
  needs: ['test_lambda']
  dependencies:
    - test_lambda
  # rules:
  #   - if: '$CI_COMMIT_BRANCH == "staging"'
  #     changes:
  #       - backend/apis/**/*
  stage: build
  environment:
    name: staging
  script:
    - *common_install
    - npm run package:staging

build_prod:
  artifacts:
    expose_as: 'backend-build'
    name: 'backend-build'
    paths: 
      - $PWD/backend/apis/.serverless/jngpaypal.zip
  needs: ['test_lambda']
  dependencies:
    - test_lambda
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      changes:
        - backend/apis/**/*
  stage: build
  environment:
    name: production
  script:
    - *common_install
    - npm run package
