cache: 
  paths:
    - backend/cdk/node_modules/

test_cdk:
  stage: test-cdk
  image: node:20.11.1
  dependencies:
    - build_staging
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      changes:
        - backend/cdk/**/*
        - backend/apis/**/*
  script:
    - cd backend/cdk
    - npm i
    - npm run test